global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram'
  routes:
    - receiver: "slack"
      group_wait: 10s
      match_re:
        severity: critical|warning
      continue: true
    - receiver: "telegram"
      group_wait: 10s
      match_re:
        severity: critical
      continue: true
receivers:
- name: "slack"
  slack_configs:
  - api_url: '< YOUR SLACK WEBHOOK >'
    send_resolved: true
    channel: '< YOUR SLACK CHANNEL >'
    text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
- name: 'telegram'
  webhook_configs:
  - send_resolved: True
    url: http://prometheus_bot:9087/alert/< CHAT ID >
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

